/**
 * Generates dist/sitemap.xml at build time.
 *
 * Hand-maintained sitemaps go stale the moment someone adds a page and forgets.
 * This runs on every build, so `lastmod` is always honest and a new route only
 * has to be added to ROUTES below.
 *
 * IMPORTANT: use query params, never `#fragments`. Search engines strip
 * fragments, so `/#privacy` would be indexed as a duplicate of the homepage.
 * App.tsx resolves `?page=privacy` and `?page=terms` directly.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = process.env.SITE_URL || 'https://www.invoix.app';

/**
 * @typedef {{ path: string, changefreq: string, priority: string }} Route
 * Add new indexable pages here — including the per-industry template pages when
 * those land. Anything gated behind auth (studio, admin) must NOT be listed.
 * @type {Route[]}
 */
const ROUTES = [
  { path: '/', changefreq: 'daily', priority: '1.0' },
  { path: '/?page=privacy', changefreq: 'monthly', priority: '0.5' },
  { path: '/?page=terms', changefreq: 'monthly', priority: '0.5' },
];

const lastmod = new Date().toISOString().slice(0, 10);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  (r) => `  <url>
    <loc>${SITE}${r.path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`
).join('\n')}
</urlset>
`;

const outDir = resolve(ROOT, 'dist');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'sitemap.xml'), xml, 'utf8');

console.log(`sitemap.xml: ${ROUTES.length} routes, lastmod ${lastmod}`);
